### ISSUE TITLE
Questions regarding production use of this project

### ISSUE THREAD

**Issue by fpemud** [virtualsquare/fusefatfs#1]
Hello there,

I am looking to mount storage devices with various old Windows FAT filesystems on Linux system using FUSE.

After an extensive search, I have found that this project is the only one capable of mounting all FAT12/16/32 filesystems and is actively maintained.

Before trying this project and deploying it in a production environment, could you kindly answer a few questions for me?
1. Can this project handle all types of encodings (codepages), similar to the vfat module in Linux kernel?
2. Can it perform write operations safely? (I ask this because the mount example in README has "-o ro" in it)
3. It's great to see that exFAT is also supported. Are all exFAT feautres supported? or is it better for me to use [this project](https://github.com/relan/exfat) to mount exfat devices?

Additionally, given that this project is currently at version 0.15, is there a roadmap or TODO list available?

Thank you.

**Comment by rd235** [comment]
Q: Can this project handle all types of encodings (codepages), similar to the vfat module in Linux kernel?
A: It should manage the codepages supported by FatFS:
http://elm-chan.org/fsw/ff/doc/config.html#code_page

Q: Can it perform write operations safely? (I ask this because the mount example in README has "-o ro" in it
A: This is NOT production code. Not yet. The idea is to work to get a quite reliable tool.
FuseFatFS has been designed to add a very simple fuse glue code layer to a well known and widely adopted implementation of a FAT file system library for embedded systems (FatFS).
FuseFatFS is *not* highly efficient, this is not the goal.
We welcome beta testers.
A legalese note. FuseFatFS has been released under the GPL2+ license so:
"This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY"

Q: It's great to see that exFAT is also supported....
A: fusefatfs supports all the exFAT features implemented in FatFS.

Q: this project is currently at version 0.15, is there a roadmap or TODO list available?
A: 0.15 is the version of FatFS. FuseFatFS 0.2 has just been uploaded.
TODO: test the code. roadmap: we release it when it's ready ;-)
